[2023-10-30T15:15:07.142+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T15:11:01.251180+00:00 [queued]>
[2023-10-30T15:15:07.158+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T15:11:01.251180+00:00 [queued]>
[2023-10-30T15:15:07.159+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 5
[2023-10-30T15:15:07.181+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): asteroides-etl-task> on 2023-10-30 15:11:01.251180+00:00
[2023-10-30T15:15:07.190+0000] {standard_task_runner.py:57} INFO - Started process 1534 to run task
[2023-10-30T15:15:07.194+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'asteroides-etl-dag', 'asteroides-etl-task', 'manual__2023-10-30T15:11:01.251180+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/asteroides-etl_dag.py', '--cfg-path', '/tmp/tmpio0_rr_h']
[2023-10-30T15:15:07.195+0000] {standard_task_runner.py:85} INFO - Job 116: Subtask asteroides-etl-task
[2023-10-30T15:15:07.261+0000] {task_command.py:416} INFO - Running <TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T15:11:01.251180+00:00 [running]> on host d87e86d3d093
[2023-10-30T15:15:07.360+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Norman Ruiz' AIRFLOW_CTX_DAG_ID='asteroides-etl-dag' AIRFLOW_CTX_TASK_ID='asteroides-etl-task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-30T15:11:01.251180+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-30T15:11:01.251180+00:00'
[2023-10-30T15:15:07.362+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-30T15:15:07.363+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run -it asteroides-etl']
[2023-10-30T15:15:07.382+0000] {subprocess.py:86} INFO - Output:
[2023-10-30T15:15:07.412+0000] {subprocess.py:93} INFO - the input device is not a TTY
[2023-10-30T15:15:07.415+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-30T15:15:07.432+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-30T15:15:07.438+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=asteroides-etl-dag, task_id=asteroides-etl-task, execution_date=20231030T151101, start_date=20231030T151507, end_date=20231030T151507
[2023-10-30T15:15:07.455+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 116 for task asteroides-etl-task (Bash command failed. The command returned a non-zero exit code 1.; 1534)
[2023-10-30T15:15:07.487+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T15:15:07.510+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
