[2023-10-30T15:06:57.039+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-10-30T15:06:57.059+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-06-07T00:00:00+00:00 [queued]>
[2023-10-30T15:06:57.059+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 5
[2023-10-30T15:06:57.099+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): asteroides-etl-task> on 2023-06-07 00:00:00+00:00
[2023-10-30T15:06:57.109+0000] {standard_task_runner.py:57} INFO - Started process 553 to run task
[2023-10-30T15:06:57.114+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'asteroides-etl-dag', 'asteroides-etl-task', 'scheduled__2023-06-07T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/asteroides-etl_dag.py', '--cfg-path', '/tmp/tmpt3z_ljfq']
[2023-10-30T15:06:57.119+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask asteroides-etl-task
[2023-10-30T15:06:57.204+0000] {task_command.py:416} INFO - Running <TaskInstance: asteroides-etl-dag.asteroides-etl-task scheduled__2023-06-07T00:00:00+00:00 [running]> on host d87e86d3d093
[2023-10-30T15:06:57.320+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Norman Ruiz' AIRFLOW_CTX_DAG_ID='asteroides-etl-dag' AIRFLOW_CTX_TASK_ID='asteroides-etl-task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-07T00:00:00+00:00'
[2023-10-30T15:06:57.322+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-30T15:06:57.324+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run -it --name asteroides-etl asteroides-etl']
[2023-10-30T15:06:57.345+0000] {subprocess.py:86} INFO - Output:
[2023-10-30T15:06:57.388+0000] {subprocess.py:93} INFO - the input device is not a TTY
[2023-10-30T15:06:57.392+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-30T15:06:57.412+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-30T15:06:57.419+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=asteroides-etl-dag, task_id=asteroides-etl-task, execution_date=20230607T000000, start_date=20231030T150657, end_date=20231030T150657
[2023-10-30T15:06:57.442+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 40 for task asteroides-etl-task (Bash command failed. The command returned a non-zero exit code 1.; 553)
[2023-10-30T15:06:57.490+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T15:06:57.520+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
