[2023-10-30T15:11:03.273+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T15:09:16.230190+00:00 [queued]>
[2023-10-30T15:11:03.301+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T15:09:16.230190+00:00 [queued]>
[2023-10-30T15:11:03.302+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 5
[2023-10-30T15:11:03.365+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): asteroides-etl-task> on 2023-10-30 15:09:16.230190+00:00
[2023-10-30T15:11:03.379+0000] {standard_task_runner.py:57} INFO - Started process 1069 to run task
[2023-10-30T15:11:03.397+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'asteroides-etl-dag', 'asteroides-etl-task', 'manual__2023-10-30T15:09:16.230190+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/asteroides-etl_dag.py', '--cfg-path', '/tmp/tmp0w5hbifq']
[2023-10-30T15:11:03.405+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask asteroides-etl-task
[2023-10-30T15:11:03.557+0000] {task_command.py:416} INFO - Running <TaskInstance: asteroides-etl-dag.asteroides-etl-task manual__2023-10-30T15:09:16.230190+00:00 [running]> on host d87e86d3d093
[2023-10-30T15:11:03.795+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Norman Ruiz' AIRFLOW_CTX_DAG_ID='asteroides-etl-dag' AIRFLOW_CTX_TASK_ID='asteroides-etl-task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-30T15:09:16.230190+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-30T15:09:16.230190+00:00'
[2023-10-30T15:11:03.800+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-30T15:11:03.802+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run -it asteroides-etl']
[2023-10-30T15:11:03.832+0000] {subprocess.py:86} INFO - Output:
[2023-10-30T15:11:03.880+0000] {subprocess.py:93} INFO - the input device is not a TTY
[2023-10-30T15:11:03.884+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-30T15:11:03.914+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-30T15:11:03.927+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=asteroides-etl-dag, task_id=asteroides-etl-task, execution_date=20231030T150916, start_date=20231030T151103, end_date=20231030T151103
[2023-10-30T15:11:03.966+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 80 for task asteroides-etl-task (Bash command failed. The command returned a non-zero exit code 1.; 1069)
[2023-10-30T15:11:04.001+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T15:11:04.033+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
